image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  untracked: true
  key: momba-pip-cache
  paths:
    - .cache/

check:
  stage: build
  script:
    - pip install tox
    - tox

docs:
  stage: build
  artifacts:
    paths:
      - build/docs
    expire_in: 1 week
  script:
    - pip install tox
    - tox -e docs
