[tool.poetry]
name = "momba"
version = "0.2.3"
description = "A Python library for quantitative models."
authors = [
    "Maximilian Köhl <koehl@cs.uni-saarland.de>"
]
license = "MIT"
readme = "README.md"
repository = "https://dgit.cs.uni-saarland.de/koehlma/momba.git"
homepage = "https://depend.cs.uni-saarland.de/~koehl/momba/"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 2 - Pre-Alpha",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.8"
click = {version = "^7.0", optional = true}
mxu = "^0.0.6"
immutables = "^0.14"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"
black = { version = "^20.8b1", allow-prereleases = true }
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.2"
pep8-naming = "^0.9.1"
mypy = "^0.800"
tox = "^3.14.3"
sphinx = "^3.4.3"
poetry = "^1.0.10"
maturin = "^0.9.0"
sphinx-autobuild = "^2020.9.1"
furo = "^2020.12.30-beta.24"
myst-parser = "^0.13.3"
jupyter_sphinx = "^0.3.2"

[tool.poetry.scripts]
momba-moml = "momba.moml.__main__:main"

[tool.poetry.extras]
cli = ["click"]
engine = ["momba_engine"]
all = ["click", "momba_engine"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
