name: Run Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry 
        poetry export --without-hashes --dev -f requirements.txt --output requirements.txt
        rustup default nightly
        pip install -r requirements.txt
    - name: Build and install Momba Engine
      run: |
        cd engine
        maturin build -i
        cd ..
        pip install target/wheels/*.tar.gz
    - name: Install Momba
      run: |
        poetry build -f wheel
        pip install dist/*.whl
    - name: Run tests
      run: |
        pytest
