name: Run Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry 
        poetry export --dev -f requirements.txt --output requirements.txt
        pip install -r requirements.txt
    - name: Install Momba
      run: |
        poetry build -f wheel
        pip install dist/*.whl
    - name: Run tests
      run: |
        pytest
